---
- hosts: localhost
  become: yes
  become_user: "{{ lookup('env', 'USER') }}"
      
  tasks:
    - name: install baseline packages
      become_user: root
      apt:
        name: "{{ item }}"
      with_items: 
        - curl 

    - import_tasks: tasks/rust_setup.yml
    - import_tasks: tasks/alacritty_setup.yml
    - import_tasks: tasks/tmux_setup.yml    
    - import_tasks: tasks/zshell_setup.yml
    - import_tasks: tasks/yubikey_ssh_setup.yml