---
- hosts: localhost
  become: yes
  become_user: "{{ lookup('env', 'USER') }}"
  vars:
    yubikey_dependencies: 
      - gnupg2 
      - scdaemon 
      - pcscd 
      
  tasks:
    - import_tasks: tasks/zshell_setup.yml
    - import_tasks: tasks/yubikey_ssh_setup.yml