---
- name: add yubikey deps
  apt:
    name: "{{ item }}"
  with_items: "{{ yubikey_dependencies }}"

- name: enable ssh for gpg-agent
  lineinfile:
    path: ~/.gnupg/gpg-agent.conf
    line: enable-ssh-support
    create: yes

- name: add ssh auth sock config to bashrc
  lineinfile:
    path: ~/.bashrc
    line: export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
